### ISSUE TITLE
作者你好，请问这个怎么解决

### ISSUE THREAD

**Issue by startwang23** [1234ab5678/UNet3Plus#1]
Traceback (most recent call last):
  File "D:\unet3\UNet3Plus-main\UNet3Plus-main\train.py", line 494, in <module>
    flag=fit_one_epoch(model_train, model, loss_history, eval_callback, optimizer, epoch, 
  File "D:\unet3\UNet3Plus-main\UNet3Plus-main\utils\utils_fit.py", line 89, in fit_one_epoch
    main_dice = Dice_loss(outputs, pngs)
  File "D:\unet3\UNet3Plus-main\UNet3Plus-main\nets\UNet3Plus_training.py", line 286, in Dice_loss
    nt, ht, wt, ct = target.size()
ValueError: not enough values to unpack (expected 4, got 3)
Epoch 1/120:   0%|          | 0/15 [00:02<?, ?it/s<class 'dict'>]

**Comment by yddjh** [comment]
我也有一样的问题
